const events = [
  {
    title: "Neil Gaiman Event",
    location: "British Library, London",
    time: "17:00",
    date: "2024-08-15",
    description:
      "Join us for an evening with Neil Gaiman, where he will be discussing his latest novel and answering questions from the audience. Book signing to follow.",
    createdAt: "2024-07-09T14:30:00Z",
    staffUsername: "john_doe",
    category: "Author Meet and Greet",
    payAsYouFeel: false,
    price: 20.0,
  },
  {
    title: "Harry Potter Trivia Night",
    location: "Bookworm Café, Edinburgh",
    time: "19:00",
    date: "2024-09-10",
    description:
      "Test your knowledge of the Harry Potter series with our exciting trivia night. Prizes for the top three teams!",
    createdAt: "2024-07-09T14:35:00Z",
    staffUsername: "jane_smith",
    category: "Book Trivia Night",
    payAsYouFeel: true,
  },
  {
    title: "The Winds of Winter Book Launch",
    location: "The Book Nook, Manchester",
    time: "15:00",
    date: "2024-10-01",
    description:
      "Celebrate the launch of 'The Winds of Winter' by George R.R. Martin. Get your copy signed and enjoy a reading from the book.",
    createdAt: "2024-07-09T14:40:00Z",
    staffUsername: "emma_brown",
    category: "Book Launch",
    payAsYouFeel: false,
    price: 30.0,
  },
  {
    title: "Carol Ann Duffy Poetry Reading",
    location: "Waterstones, Glasgow",
    time: "18:00",
    date: "2024-11-05",
    description:
      "Join us for an evening of poetry with Carol Ann Duffy, the former Poet Laureate. A reading session followed by a Q&A.",
    createdAt: "2024-07-09T14:45:00Z",
    staffUsername: "michael_jones",
    category: "Poetry Reading",
    payAsYouFeel: true,
  },
  {
    title: "Jane Austen Day",
    location: "Chawton House, Alton",
    time: "10:00",
    date: "2024-08-20",
    description:
      "Celebrate the life and works of Jane Austen with a day of readings, workshops, and tours at Chawton House.",
    createdAt: "2024-07-09T14:50:00Z",
    staffUsername: "sarah_clark",
    category: "Literary Festival",
    payAsYouFeel: false,
    price: 10.0,
  },
  {
    title: "Isaac Asimov Sci-Fi Convention",
    location: "Excel London, London",
    time: "09:00",
    date: "2024-09-15",
    description:
      "Join us for a day dedicated to the works of Isaac Asimov. Panel discussions, book signings, and cosplay.",
    createdAt: "2024-07-09T14:55:00Z",
    staffUsername: "david_wilson",
    category: "Literary Festival",
    payAsYouFeel: false,
    price: 25.0,
  },
  {
    title: "Roald Dahl Storytime",
    location: "The Story Museum, Oxford",
    time: "11:00",
    date: "2024-10-05",
    description:
      "Bring your children for a magical storytime session featuring the works of Roald Dahl. Fun activities and a reading.",
    createdAt: "2024-07-09T15:00:00Z",
    staffUsername: "john_doe",
    category: "Literary Festival",
    payAsYouFeel: true,
  },
  {
    title: "J.K. Rowling Book Signing",
    location: "Waterstones, Birmingham",
    time: "14:00",
    date: "2024-11-15",
    description: "Meet J.K. Rowling and get your favorite book signed. Limited tickets available, so book early!",
    createdAt: "2024-07-09T15:05:00Z",
    staffUsername: "jane_smith",
    category: "Book Signing",
    payAsYouFeel: false,
    price: 50.0,
  },
  {
    title: "Hilary Mantel Historical Fiction Workshop",
    location: "University of Edinburgh, Edinburgh",
    time: "13:00",
    date: "2024-08-25",
    description:
      "Join Hilary Mantel for an exclusive workshop on writing historical fiction. Insights, tips, and interactive sessions.",
    createdAt: "2024-07-09T15:10:00Z",
    staffUsername: "emma_brown",
    category: "Writing Workshop",
    payAsYouFeel: false,
    price: 75.0,
  },
  {
    title: "Alan Moore Graphic Novel Day",
    location: "Forbidden Planet, London",
    time: "16:00",
    date: "2024-09-20",
    description: "Celebrate graphic novels with Alan Moore. Discussions, Q&A, and a book signing session.",
    createdAt: "2024-07-09T15:15:00Z",
    staffUsername: "michael_jones",
    category: "Literary Festival",
    payAsYouFeel: true,
  },
  {
    title: "Patrick Rothfuss Fantasy Fiction Panel",
    location: "Blackwell's, Oxford",
    time: "18:00",
    date: "2024-10-10",
    description:
      "Join Patrick Rothfuss and other fantasy authors for an engaging panel discussion on the art of fantasy writing.",
    createdAt: "2024-07-09T15:20:00Z",
    staffUsername: "sarah_clark",
    category: "Writing Workshop",
    payAsYouFeel: false,
    price: 20.0,
  },
  {
    title: "Mystery Writers' Symposium",
    location: "The National Centre for Writing, Norwich",
    time: "10:00",
    date: "2024-11-20",
    description: "A full day symposium featuring top mystery writers. Panels, workshops, and networking opportunities.",
    createdAt: "2024-07-09T15:25:00Z",
    staffUsername: "david_wilson",
    category: "Writing Workshop",
    payAsYouFeel: false,
    price: 40.0,
  },
];

export default events;
